### ISSUE TITLE
Resolve warning when using rg function

### ISSUE THREAD

**Issue by jmadin** [jmadinlab/habtools#26]
I get the following warning a lot, and need to work out why:

`Warning message:
In split_dem(data, L0, parallel = parallel, ncores = ncores) :
  With the specified size, the RasterLayer is not divided across the full extent`

**Comment by nschiett** [comment]
I replaced the warning by a message and made things more informative. It now says: "With the specified size, the RasterLayer is not divided across the full extent. Consider a value for L0 so that L/L0 is a whole number and L0 is either equal to the resolution or a multiplicative of the resolution. "

**Comment by jmadin** [comment]
Correct planar area in calculation when not calculated over entire extent.
